services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Haassie\PageSpeedInsights\:
    resource: '../Classes/*'

  dashboard.widget.lighthouse.accessibilityScore:
    class: 'TYPO3\CMS\Dashboard\Widgets\DoughnutChartWidget'
    arguments:
      $dataProvider: 'Haassie\PageSpeedInsights\Widgets\Provider\AccessibilityScoreDataProvider'
      $view: '@dashboard.views.widget'
    tags:
      - name: dashboard.widget
        identifier: 'lighthouseAccessibility'
        groupNames: 'psi'
        title: 'LLL:EXT:page_speed_insights/Resources/Private/Language/locallang.xlf:widgets.accessibility.title'
        description: 'LLL:EXT:page_speed_insights/Resources/Private/Language/locallang.xlf:widgets.accessibility.description'
        iconIdentifier: 'content-widget-chart-pie'
        additionalCssClasses: 'dashboard-item--chart'
        height: 1
        width: 1

#
#  Haassie\PageSpeedInsights\Widgets\LighthouseAccessibilityScoreWidget:
#    arguments: ['lighthouseAccessibility']
#    tags:
#      - name: dashboard.widget
#        identifier: lighthouseAccessibility
#        widgetGroups: 'psi'
#
#  Haassie\PageSpeedInsights\Widgets\LighthouseBestPracticesScoreWidget:
#    arguments: ['lighthouseBestPractices']
#    tags:
#      - name: dashboard.widget
#        identifier: lighthouseBestPractices
#        widgetGroups: 'psi'
#
#  Haassie\PageSpeedInsights\Widgets\LighthousePerformanceScoreWidget:
#    arguments: ['lighthousePerformance']
#    tags:
#      - name: dashboard.widget
#        identifier: lighthousePerformance
#        widgetGroups: 'psi'
#
#  Haassie\PageSpeedInsights\Widgets\LighthousePwaScoreWidget:
#    arguments: ['lighthousePwa']
#    tags:
#      - name: dashboard.widget
#        identifier: lighthousePwa
#        widgetGroups: 'psi'
#
#  Haassie\PageSpeedInsights\Widgets\LighthouseSeoScoreWidget:
#    arguments: ['lighthouseSeo']
#    tags:
#      - name: dashboard.widget
#        identifier: lighthouseSeo
#        widgetGroups: 'psi'
#
#  Haassie\PageSpeedInsights\Widgets\LighthouseScoreHistoryWidget:
#    arguments: ['lighthouseScoreHistory']
#    tags:
#      - name: dashboard.widget
#        identifier: lighthouseScoreHistory
#        widgetGroups: 'psi'
